export const researchQuestions = [
  "How can normal multivariate IoT sensor behaviour be represented to support the detection of sensor-data integrity attacks?",
  "How effectively can lightweight anomaly-detection methods detect different forms of sensor-data manipulation compared with a statistical baseline?",
  "What trade-offs arise between attack-detection performance and edge-resource consumption when detection is executed on a resource-constrained IoT gateway?",
];

export const researchMethods = ["Statistical Baseline", "Isolation Forest", "One-Class SVM"];
export const researchScenarios = ["Spike / False-Data Injection", "Persistent Bias", "Gradual Drift", "Stuck / Frozen Values"];
export const repositoryUrl = "https://github.com/Elkaza/secure-edge-ai-iot-gateway";

export const projectText = {
  de: {
    back: "Zur Forschungsübersicht", status: "In Arbeit", scope: "Arbeitstitel · aktueller Forschungsumfang; finale Abstimmung mit der Betreuung steht aus.",
    overviewTitle: "Kurzbeschreibung",
    overview: "IoT-Sensorsysteme erzeugen kontinuierlich Betriebsdaten. Manipulierte Messwerte können deren Integrität und darauf aufbauende Entscheidungen beeinträchtigen. Das Projekt untersucht, ob leichtgewichtige Anomalieerkennung direkt auf einem ressourcenbeschränkten Edge Gateway möglich ist. Umweltsensordaten dienen als legitime Verhaltensbasis und experimentelle Arbeitslast; allgemeine Umweltanomalien sind nicht das primäre Forschungsproblem. Kontrollierte Manipulationen werden ausschließlich im isolierten Forschungstestbed erzeugt. Geplant ist die Evaluierung von Erkennungsleistung und Ressourcenbedarf.",
    objectiveTitle: "Forschungsziel", objective: "Ziel ist der Entwurf und die experimentelle Evaluierung eines reproduzierbaren Prototyps für lokales Sicherheitsmonitoring von Sensor-Data Integrity. Leichtgewichtige statistische und Machine-Learning-Verfahren sollen Manipulationen von Sensorbeobachtungen erkennen. Implementierung und experimentelle Ergebnisse stehen noch aus.",
    questionsTitle: "Forschungsfragen", draft: "Aktueller Entwurf",
    architectureTitle: "Systemarchitektur", architecture: "Geplanter Live-Datenpfad: ASAIR AM2302 → ESP32-S3 → Wi-Fi / MQTT → unveränderte Weiterleitung oder Controlled Attack Injection → Raspberry Pi 5 Edge Security Gateway → statistische / ML-Erkennung → Normalzustand oder Sicherheitsalarm. Historische Umweltdaten können nach Klärung des Zugangs kontrolliert in dasselbe Isolated Research Testbed eingespielt werden. Die FH-Produktionsinfrastruktur liegt ausdrücklich außerhalb des Angriffsumfangs.",
    experimentTitle: "Experimenteller Ansatz", experiment: "Legitime Sensordaten → Vorverarbeitung → Modellierung normalen Verhaltens → Controlled Attack Injection → unabhängiger Vergleich der Erkennungsverfahren → Ausführung auf dem Raspberry Pi 5 → Evaluierung von Erkennungsleistung und Ressourcenbedarf. RQ1 adressiert die Verhaltensmodellierung, RQ2 den Methodenvergleich und die Erkennungsleistung, RQ3 die Edge-Ausführung und Ressourcenmessung.",
    methodsTitle: "Untersuchte Verfahren", methods: "Im geplanten Vergleich dient die Statistical Baseline als transparente Referenz. Isolation Forest und One-Class SVM bieten alternative Ansätze, um Abweichungen vom normalen Sensorverhalten zu erkennen. Pro Experiment wird ein Verfahren unabhängig evaluiert; eine Rangfolge ist noch nicht bekannt.",
    scenariosTitle: "Kontrollierte Angriffsszenarien", scenarios: "Die folgenden Manipulationen sind ausschließlich als kontrollierte Experimente im isolierten Forschungstestbed vorgesehen.", optionalReplay: "Replay — optionales späteres Experiment",
    platformTitle: "Testplattform", software: "Software / Protokolle (geplant)", hardware: "Hardware", hardwareItems: ["Raspberry Pi 5", "ESP32-S3-DevKitC-1", "ASAIR AM2302", "microSD-Speicher und lokales Netzwerk"],
    evaluationTitle: "Evaluierung", evaluation: "Untersucht werden die Zielkonflikte zwischen Erkennungsleistung und Rechenaufwand am Edge Gateway. Messergebnisse liegen noch nicht vor.", detection: "Erkennungsleistung", resources: "Edge-Ressourcen", delay: "Detection Delay, soweit anwendbar",
    boundaryTitle: "Abgrenzung", boundary: "Im Umfang liegt Sensor-Data Integrity Monitoring durch kontrollierte Manipulation von Sensorbeobachtungen. Ausgeschlossen sind allgemeine IDS, Malware-Erkennung, Firmware-Exploits, WLAN- und Passwortangriffe, MQTT-Broker-Exploits, kryptografische Angriffe sowie Angriffe auf die FH-Produktionsinfrastruktur.",
    statusTitle: "Aktueller Stand", available: "Vorhanden / konzipiert", next: "In Vorbereitung / geplant", availableItems: ["Initialer Forschungsumfang definiert", "Raspberry Pi 5, ESP32-S3 und ASAIR AM2302 verfügbar", "Initiale Systemarchitektur und Forschungsmethodik entworfen"], nextItems: ["Finale Abstimmung des Forschungsumfangs und Klärung des Datenzugangs", "Testbed-Aufbau und Datenerfassung", "Statistische Baseline und ML-Experimente", "Edge-Benchmarking"], fullSize: "Diagramm in Originalgröße öffnen",
  },
  en: {
    back: "Back to research", status: "In progress", scope: "Working title · current research scope; final alignment with the supervisor is pending.",
    overviewTitle: "Overview", overview: "IoT sensor systems continuously generate operational data. Manipulated observations can compromise data integrity and downstream decisions. This project investigates whether lightweight anomaly detection can run directly on a resource-constrained edge gateway. Environmental sensor data provides the legitimate behavioural baseline and experimental workload; generic environmental anomaly detection is not the primary research problem. Controlled manipulations will be generated only in an isolated research testbed. Evaluation will cover detection effectiveness and edge-resource usage.",
    objectiveTitle: "Research objective", objective: "The objective is to design and experimentally evaluate a reproducible edge-based security monitoring prototype for Sensor-Data Integrity using lightweight statistical and machine-learning approaches. Implementation and experimental results are still pending.",
    questionsTitle: "Research questions", draft: "Current draft",
    architectureTitle: "System architecture", architecture: "Planned live path: ASAIR AM2302 → ESP32-S3 → Wi-Fi / MQTT → pass-through or Controlled Attack Injection → Raspberry Pi 5 Edge Security Gateway → statistical / ML detection → normal or security alert. Historical environmental data may be replayed into the same Isolated Research Testbed once access is clarified. FH production infrastructure is outside the attack scope.",
    experimentTitle: "Experimental approach", experiment: "Legitimate sensor data → preprocessing → normal-behaviour modelling → Controlled Attack Injection → independent comparison of detection methods → Raspberry Pi 5 deployment → detection and resource evaluation. RQ1 maps to normal-behaviour modelling; RQ2 to detection methods and detection evaluation; RQ3 to edge deployment and resource evaluation.",
    methodsTitle: "Planned detection methods", methods: "The Statistical Baseline provides a transparent reference. Isolation Forest and One-Class SVM offer alternative approaches to identifying deviations from normal sensor behaviour. One method will be evaluated independently per experiment; no ranking has been established.",
    scenariosTitle: "Controlled security scenarios", scenarios: "These manipulations are planned exclusively as controlled experiments inside the isolated research testbed.", optionalReplay: "Replay — optional later experiment",
    platformTitle: "Experimental platform", software: "Software / protocols (planned)", hardware: "Hardware", hardwareItems: ["Raspberry Pi 5", "ESP32-S3-DevKitC-1", "ASAIR AM2302", "microSD storage and local networking"],
    evaluationTitle: "Evaluation", evaluation: "The study will investigate the trade-off between detection effectiveness and computational cost at the edge gateway. No measurement results are available yet.", detection: "Detection effectiveness", resources: "Edge resources", delay: "Detection Delay, where applicable",
    boundaryTitle: "Research scope", boundary: "Sensor-Data Integrity Monitoring through controlled manipulation of sensor observations is in scope. Generic IDS, malware detection, firmware exploitation, Wi-Fi attacks, credential attacks, MQTT broker exploitation, cryptographic attacks and attacks against FH production infrastructure are outside scope.",
    statusTitle: "Current status", available: "Available / designed", next: "In preparation / planned", availableItems: ["Initial research scope defined", "Raspberry Pi 5, ESP32-S3 and ASAIR AM2302 available", "Initial system architecture and research methodology designed"], nextItems: ["Final scope alignment and data-access clarification", "Testbed setup and data acquisition", "Statistical baseline implementation and ML experiments", "Edge benchmarking"], fullSize: "Open original-size diagram",
  },
};
